/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedSlugRouteImport } from './routes/shared.$slug'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedStudyGuideRouteImport } from './routes/_authenticated/study-guide'
import { Route as AuthenticatedQuizzesRouteImport } from './routes/_authenticated/quizzes'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedSetsRouteImport } from './routes/_authenticated/sets'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedStudySetIdRouteImport } from './routes/_authenticated/study.$setId'
import { Route as AuthenticatedEditorSetIdRouteImport } from './routes/_authenticated/editor.$setId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedSlugRoute = SharedSlugRouteImport.update({
  id: '/shared/$slug',
  path: '/shared/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudyGuideRoute = AuthenticatedStudyGuideRouteImport.update({
  id: '/study-guide',
  path: '/study-guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizzesRoute = AuthenticatedQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetsRoute = AuthenticatedSetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudySetIdRoute = AuthenticatedStudySetIdRouteImport.update({
  id: '/study/$setId',
  path: '/study/$setId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditorSetIdRoute =
  AuthenticatedEditorSetIdRouteImport.update({
    id: '/editor/$setId',
    path: '/editor/$setId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/quizzes': typeof AuthenticatedQuizzesRoute
  '/study-guide': typeof AuthenticatedStudyGuideRoute
  '/shared/$slug': typeof SharedSlugRoute
  '/editor/$setId': typeof AuthenticatedEditorSetIdRoute
  '/study/$setId': typeof AuthenticatedStudySetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/quizzes': typeof AuthenticatedQuizzesRoute
  '/study-guide': typeof AuthenticatedStudyGuideRoute
  '/shared/$slug': typeof SharedSlugRoute
  '/editor/$setId': typeof AuthenticatedEditorSetIdRoute
  '/study/$setId': typeof AuthenticatedStudySetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/quizzes': typeof AuthenticatedQuizzesRoute
  '/_authenticated/study-guide': typeof AuthenticatedStudyGuideRoute
  '/shared/$slug': typeof SharedSlugRoute
  '/_authenticated/editor/$setId': typeof AuthenticatedEditorSetIdRoute
  '/_authenticated/study/$setId': typeof AuthenticatedStudySetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create'
    | '/dashboard'
    | '/flashcards'
    | '/progress'
    | '/quizzes'
    | '/study-guide'
    | '/shared/$slug'
    | '/editor/$setId'
    | '/study/$setId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/dashboard'
    | '/flashcards'
    | '/progress'
    | '/quizzes'
    | '/study-guide'
    | '/shared/$slug'
    | '/editor/$setId'
    | '/study/$setId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/create'
    | '/_authenticated/dashboard'
    | '/_authenticated/flashcards'
    | '/_authenticated/progress'
    | '/_authenticated/quizzes'
    | '/_authenticated/study-guide'
    | '/shared/$slug'
    | '/_authenticated/editor/$setId'
    | '/_authenticated/study/$setId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SharedSlugRoute: typeof SharedSlugRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$slug': {
      id: '/shared/$slug'
      path: '/shared/$slug'
      fullPath: '/shared/$slug'
      preLoaderRoute: typeof SharedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/study-guide': {
      id: '/_authenticated/study-guide'
      path: '/study-guide'
      fullPath: '/study-guide'
      preLoaderRoute: typeof AuthenticatedStudyGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes': {
      id: '/_authenticated/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AuthenticatedQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study/$setId': {
      id: '/_authenticated/study/$setId'
      path: '/study/$setId'
      fullPath: '/study/$setId'
      preLoaderRoute: typeof AuthenticatedStudySetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editor/$setId': {
      id: '/_authenticated/editor/$setId'
      path: '/editor/$setId'
      fullPath: '/editor/$setId'
      preLoaderRoute: typeof AuthenticatedEditorSetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedSetsRoute: typeof AuthenticatedSetsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedQuizzesRoute: typeof AuthenticatedQuizzesRoute
  AuthenticatedStudyGuideRoute: typeof AuthenticatedStudyGuideRoute
  AuthenticatedEditorSetIdRoute: typeof AuthenticatedEditorSetIdRoute
  AuthenticatedStudySetIdRoute: typeof AuthenticatedStudySetIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedSetsRoute: AuthenticatedSetsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedQuizzesRoute: AuthenticatedQuizzesRoute,
  AuthenticatedStudyGuideRoute: AuthenticatedStudyGuideRoute,
  AuthenticatedEditorSetIdRoute: AuthenticatedEditorSetIdRoute,
  AuthenticatedStudySetIdRoute: AuthenticatedStudySetIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SharedSlugRoute: SharedSlugRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
